version: "1.0"
# настроить env file
services:

  db:
    image: postgres:16.1
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
    ports:
      - "5432:5432"

  app:
    env_file:
      - ../.env
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8080:8000
